don't collect cached wheels

diff --git a/builder/scripts/collect-build-files b/builder/scripts/collect-build-files
--- a/builder/scripts/collect-build-files
+++ b/builder/scripts/collect-build-files
@@ -13,16 +13,18 @@ USAGE:
     $0 [OPTIONS] SOURCE DESTINATION
 
 ARGUMENTS:
-    SOURCE                 The high-level Fromager output directory containing wheels, sdists, build
-                           sequence summary, and other files.
-    DESTINATION            The destination directory to copy the Fromager output to. Directory is
-                           created if it does not exist, or cleared otherwise.
+    SOURCE                  The high-level Fromager output directory containing wheels, sdists, build
+                            sequence summary, and other files.
+    DESTINATION             The destination directory to copy the Fromager output to. Directory is
+                            created if it does not exist, or cleared otherwise.
+    PULP_API_BASE_URL       Base URL for your PULP API.
+    PULP_REPO_ID            The ID of your PULP Repository
 
 OPTIONS:
     --help                          Show this help message
 
 EXAMPLES:
-    $0 /tmp/build-output /tmp/artifact
+    $0 /tmp/build-output /tmp/artifact https://foo.com/api/pulp/public-domain/api/v3/ 0123abcd-e1gh-ab12-ff3f-48d5805cgcc6
 
 ENVIRONMENT:
     DEBUG=1                        Enable debug mode with verbose output
@@ -52,6 +54,12 @@ while [[ $# -gt 0 ]]; do
             elif [[ -z "$DESTINATION" ]]; then
                 DESTINATION="$1"
                 shift
+            elif [[ -z "$PULP_API_BASE_URL" ]]; then
+                PULP_API_BASE_URL="$1"
+                shift
+            elif [[ -z "$PULP_REPO_ID" ]]; then
+                PULP_REPO_ID="$1"
+                shift
             else
                 echo 'Error: Unexpected number of parameters.' >&2
                 exit 1
@@ -63,6 +71,11 @@ done
 # Check if required positional argument is provided
 if [[ -z "$SOURCE" || -z "$DESTINATION" ]]; then
     echo 'Error: SOURCE and DESTINATION are both required.' >&2
+    exit 1
+fi
+
+if [[ -z "$PULP_API_BASE_URL" || -z "$PULP_REPO_ID" ]]; then
+    echo 'Error: PULP_API_BASE_URL and PULP_REPO_ID are both required.' >&2
     exit 1
 fi
 
@@ -80,11 +93,6 @@ log() {
     echo "[$(date --utc -Ins)] $1" >&2
 }
 
-#log "Setting up netrc"
-#NETRC=~/.netrc
-#cat > $NETRC <<- EOM
-#machine packages.redhat.com login ${SERVICE_ACCOUNT_USERNAME} password ${SERVICE_ACCOUNT_PASSWORD}
-#EOM
 log "Collecting build files..."
 
 # Ensure output directory is clear
@@ -93,6 +101,10 @@ rm -rf "${DESTINATION}/{*,.*}" && mkdir -p "${DESTINATION}"
 # TODO: The "downloads" name in the path is a misnomer. Those are actually built wheels.
 WHEELS_DIR="${SOURCE}/wheels-repo/downloads"
 PREBUILT_DIR="${SOURCE}/wheels-repo/prebuilt"
+
+# get most recent repository_version
+REPO_VERSION=$( curl --fail --silent --retry 3 --max-time 30 \
+    "${PULP_API_BASE_URL}repositories/python/python/${PULP_REPO_ID}/" | jq -r .latest_version_href )
 
 # Copy all built wheels, ignoring prebuilt wheels and wheels already in Pulp
 if [ -d "${WHEELS_DIR}" ]; then
@@ -109,14 +121,17 @@ if [ -d "${WHEELS_DIR}" ]; then
         fi
         
         # 2. Check if wheel already exists in Pulp
-        #log "Checking if ${FILENAME} exists in Pulp..."
-        #RESPONSE=$(curl --netrc --fail --silent "https://packages.redhat.com/api/pulp/public-trusted-libraries/api/v3/content/python/packages/?filename=${FILENAME}")
-        #if echo "$RESPONSE" | grep -q '"count":[1-9]'; then
-        #    log "Skipping ${FILENAME} - already exists in Pulp"
-        #    continue
-        #fi
+        log "Checking if ${FILENAME} exists in Pulp..."
+        WHEEL_EXISTS=$( curl --fail --silent --retry 3 --max-time 30 \
+            "${PULP_API_BASE_URL}content/python/packages/" --url-query "filename=${FILENAME}" \
+            --url-query "repository_version=${REPO_VERSION}" | jq -e '.results | length != 0' )
 
-        # check wheel type, copy valid wheels
+        if $WHEEL_EXISTS; then
+            log "Skipping ${FILENAME} - already exists in Pulp"
+            continue
+        fi
+
+        # 3. check wheel type, only collect valid wheels
         case $FILENAME in
             # pure-python or manylinux
             *none-any.whl|*manylinux*)
@@ -124,7 +139,7 @@ if [ -d "${WHEELS_DIR}" ]; then
                 cp "$file" "${DESTINATION}/"
                 ;;
             *)
-                log "Skipping collection of ${FILENAME}"
+                log "Skipping ${FILENAME} - invalid wheel type"
                 ;;
         esac;
     done
